### PR TITLE
Update default.html (add right to left support for arabic)

### PR DESCRIPTION
**Pull request by mimsadAlef**
dir for text direction
for arabic language and persian
in `_config.yml` add `dir: rtl OR ltr`

### CODE REVIEW

**Comment by mimsadAlef** [comment]
helllllloooooo

**Comment by mimsadAlef** [comment]
@benbalter

**Review by YDX-2147483647 — APPROVED** [review]
Due to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/dir), `auto` is also acceptable. However, this works too.

**Comment by mimsadAlef** [comment]
i am not access to this pull request
created a new pull

**Pull request closed without merging**
