### PR TITLE
Optimize fonts loading

### PR DESCRIPTION
**Pull request by ogonkov**
- Use `font-display: swap`
- Preload Google Fonts CSS
- Add Google Fonts URL to ignore by `htmlproofer`, to avoid false positive

### CODE REVIEW

**Comment by ogonkov** [comment]
What should happen to get this merged?

**Comment by ogonkov** [comment]
Go away bot.

**Comment by ogonkov** [comment]
@parkr can you please review this PR?

**Comment by parkr** [comment]
@ogonkov Hey, I'm afraid I'm not aware of the reasons for the changes you're making here. Could you please provide more information about why these changes are important?

**Comment by ogonkov** [comment]
This changes will make browser to preconnect to google fonts host, to decrease time to load fonts stylesheet. Also, i have added "swap" param, to make browser change font after it download, this will help to avoid flash of not loaded font.

**Review by parkr — APPROVED** [review]

**Pull request merged**
